service: talk-is-cool
useDotenv: true

frameworkVersion: '2'

custom:
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 128
  logRetentionInDays: 1
  versionFunctions: false
  lambdaHashingVersion: 20201221
  environment: ${file(envs/${self:custom.stage}.env.json)}
  layers:
    - { Ref: CoreLambdaLayer }

layers:
  Core:
    path: layers/core
    name: talk-is-cool-core-${self:custom.stage}

functions:
  auth:
    handler: src/handlers/auth.auth
    events:
      - http:
          path: auth
          method: post
          cors: true
  tags-search:
    handler: src/handlers/tags.search
    events:
      - http:
          path: tags
          method: get
          cors: true

plugins:
- serverless-offline
